name: Generate Snake

on:
  schedule: # run automatically every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual run from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Taophycc
          outputs: dist/snake.svg

      - name: Publish Snake to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
