name: WakaTime Stats

on:
  schedule:
    # Runs once every day at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch: # allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
